'use client';
import { useState } from 'react';
import { Search, SlidersHorizontal, X } from 'lucide-react';
import { products,formats,applications } from './data';
import { ProductCard } from './shared';
import BrandSelect from './select';
export default function CatalogBrowser({initialFormat=''}:{initialFormat?:string}) {
 const [query,setQuery]=useState('');const [format,setFormat]=useState(initialFormat);const [application,setApplication]=useState('');const [packaging,setPackaging]=useState('');
 const shown=products.filter(p=>(!format||p.format===format)&&(!application||p.application===application)&&(!packaging||p.packaging===packaging)&&`${p.name} ${p.ingredients} ${p.chineseName} ${p.id}`.toLowerCase().includes(query.toLowerCase().trim()));
 const filtered=Boolean(query||application||packaging||format!==initialFormat);
 const matchesText=(p:typeof products[number])=>`${p.name} ${p.ingredients} ${p.chineseName} ${p.id}`.toLowerCase().includes(query.toLowerCase().trim());
 const formatCounts=products.filter(p=>matchesText(p)&&(!application||p.application===application)&&(!packaging||p.packaging===packaging));
 const applicationCounts=products.filter(p=>matchesText(p)&&(!format||p.format===format)&&(!packaging||p.packaging===packaging));
 const packagingCounts=products.filter(p=>matchesText(p)&&(!format||p.format===format)&&(!application||p.application===application));
 return <div className="jt-browser"><div className="jt-filter-bar"><label className="jt-search"><Search size={19}/><span className="jt-sr-only">Search products</span><input type="search" placeholder="Search an ingredient or product…" value={query} onChange={e=>setQuery(e.target.value)}/></label><BrandSelect id="catalog-format" label="Format" value={format} onChange={setFormat} options={[{value:'',label:'All formats',count:formatCounts.length},...formats.map(f=>({value:f.slug,label:f.name,count:formatCounts.filter(p=>p.format===f.slug).length}))]}/><BrandSelect id="catalog-application" label="Application" value={application} onChange={setApplication} options={[{value:'',label:'All applications',count:applicationCounts.length},...applications.map(a=>({value:a.name,label:a.name,count:applicationCounts.filter(p=>p.application===a.name).length}))]}/><BrandSelect id="catalog-packaging" label="Packaging" value={packaging} onChange={setPackaging} options={[{value:'',label:'All packaging',count:packagingCounts.length},...[...new Set(products.map(p=>p.packaging))].map(p=>({value:p,label:p,count:packagingCounts.filter(x=>x.packaging===p).length}))]}/></div><div className="jt-results-bar"><p role="status" aria-live="polite"><SlidersHorizontal size={15}/> {shown.length} product {shown.length===1?'concept':'concepts'}</p>{filtered&&<button type="button" onClick={()=>{setQuery('');setFormat(initialFormat);setApplication('');setPackaging('');}}>Clear filters <X size={14}/></button>}<span>Made for your next manufacturing conversation</span></div>{shown.length?<div className="jt-product-grid">{shown.map((p,i)=><ProductCard key={p.id} product={p} priority={i<4}/>)}</div>:<div className="jt-empty"><h2>No matching concepts yet.</h2><p>Try another ingredient or clear a filter. You can also discuss a custom product with us.</p><button className="jt-button" onClick={()=>{setQuery('');setFormat('');setApplication('');setPackaging('');}}>Show all products</button><a href="/contact">Discuss a custom formula ↗</a></div>}</div>;
}
