import sourceProducts from './products.json';

export const products = sourceProducts;
export type Product = (typeof products)[number];
export const formats = [
  { slug: 'gummies', name: 'Gummies', short: 'A different kind of daily ritual.', description: 'Explore gummy concepts with ingredient, flavor, texture and packaging development considered together.', consideration: 'Review active loading, piece weight, serving size, flavor and texture. Ingredient stability and the production process need to be evaluated together.', packaging: 'Bottle presentation; count, closure and moisture protection are reviewed for the finished formula.', image: 'collagen-gummies', color: '#ede6d7' },
  { slug: 'liquid-drops', name: 'Liquid Drops', short: 'Small format. Many possibilities.', description: 'Mineral and botanical liquid concepts in dropper-bottle presentations, ready for a focused formulation discussion.', consideration: 'Define serving volume, solubility or suspension, taste and dosing device. Compatibility with the bottle and closure is part of the development review.', packaging: 'Dropper bottles; fill volume, dosing accuracy, closure and shipping protection depend on the specification.', image: 'magnesium-calcium-zinc-drops', color: '#e5eae5' },
  { slug: 'softgels', name: 'Softgels', short: 'Designed around the fill.', description: 'Oil and extract concepts with fill, shell compatibility and packaging evaluated as one system.', consideration: 'Confirm the fill composition, shell material, dimensions and target serving. Shell and fill compatibility, and the producing facility, must be agreed for the project.', packaging: 'Bottle and pouch concepts; final barrier properties and pack count require compatibility review.', image: 'pumpkin-seed-oil-softgels', color: '#e7ebdb' },
  { slug: 'oral-dissolving-films', name: 'Oral Dissolving Films', short: 'A compact delivery experience.', description: 'Iron and glutathione film concepts that connect formulation, handling and individual protective packaging.', consideration: 'Review ingredient loading, film size, taste, dissolution and moisture sensitivity. An existing capsule formula cannot simply be transferred without a new feasibility review.', packaging: 'Individually protected strips with an outer carton; barrier and sealing requirements are product-specific.', image: 'glutathione-oral-films', color: '#f1e2e6' },
  { slug: 'powders', name: 'Powders', short: 'From daily blends to focused nutrition.', description: 'Collagen, greens and single-ingredient powder concepts in pouch and canister presentations.', consideration: 'Agree the serving, ingredient form, particle characteristics, flavor and mixing expectations. Moisture protection and the measuring method influence packaging decisions.', packaging: 'Pouches and canisters; serving measure, barrier, closure and pack weight are reviewed together.', image: 'collagen-peptides-powder', color: '#e0ece9' },
  { slug: 'capsules', name: 'Capsules', short: 'A familiar, flexible starting point.', description: 'Explore a magnesium glycinate capsule concept and the decisions behind a custom capsule specification.', consideration: 'Review ingredient form, fill weight, capsule size, shell and units per serving. Confirm how the proposed ingredient amount relates to the finished-product specification.', packaging: 'Bottle presentation; capsule count, closure and moisture protection are agreed during development.', image: 'magnesium-glycinate-capsules', color: '#eee5d5' },
  { slug: 'chewable-tablets', name: 'Chewable Tablets', short: 'Formulation meets mouthfeel.', description: 'Fiber and vitamin C chewable concepts with taste, texture and serving experience at the center of development.', consideration: 'Balance the intended ingredient amount with tablet size, taste and mouthfeel. Sweetener selection, compression behavior and finished-product testing need a coordinated review.', packaging: 'Bottles with agreed tablet counts and protective closures; final dimensions follow the approved tablet.', image: 'daily-fiber-chewables', color: '#e9ecdf' },
];
export const applications = [
  { slug: 'daily-wellness', name: 'Daily wellness', title: 'Everyday nutrition, thoughtfully developed.', description: 'Explore minerals, vitamins and botanical concepts across familiar dosage formats.', image: 'magnesium-glycinate-capsules', questions: ['Who is the intended consumer?', 'Which ingredient forms and serving approach fit the brief?', 'What information does the destination market require?'] },
  { slug: 'beauty', name: 'Beauty', title: 'Beauty concepts, from the inside out.', description: 'Compare collagen and glutathione product directions across powders, gummies and oral films.', image: 'collagen-gummies', questions: ['Which ingredient sources fit the product positioning?', 'How will the serving fit the chosen format?', 'What evidence supports the proposed label wording?'] },
  { slug: 'digestive-wellness', name: 'Digestive wellness', title: 'A considered approach to daily fiber.', description: 'Start with fiber chewable concepts and review the ingredient, serving and sensory requirements.', image: 'daily-fiber-chewables', questions: ['Which fiber source and amount are being considered?', 'How do taste and serving size work together?', 'Which packaging protects the approved product?'] },
  { slug: 'sports-nutrition', name: 'Sports nutrition', title: 'Built around a practical routine.', description: 'Explore glutamine and beet root powder concepts, with serving, mixing and packaging decisions made together.', image: 'l-glutamine-powder', questions: ['What is the intended use occasion?', 'What mixing and flavor experience is required?', 'Which tests and ingredient specifications are needed?'] },
  { slug: 'relaxation', name: 'Relaxation', title: 'Start with the experience you want to create.', description: 'Review botanical concepts in gummies, drops and softgels with a product-specific feasibility assessment.', image: 'ashwagandha-gummies', questions: ['What is the target audience and market?', 'Which botanicals and ingredient specifications are proposed?', 'How will the final claims and serving be reviewed?'] },
  { slug: 'focus', name: 'Focus', title: 'Turn a cognitive concept into a clear brief.', description: 'Define the ingredients, target consumer and delivery requirements before developing a cognitive formula.', image: 'cognitive-softgels', questions: ['Which ingredients are actually included in the brief?', 'What evidence and market review will be required?', 'Which serving and packaging approach is appropriate?'] },
];
export const featuredSlugs = ['collagen-gummies','magnesium-calcium-zinc-drops','pumpkin-seed-oil-softgels','glutathione-oral-films','collagen-peptides-powder','magnesium-glycinate-capsules','daily-fiber-chewables','l-glutamine-powder'];
export const getProduct = (slug: string) => products.find(p => p.slug === slug);
export const getFormat = (slug: string) => formats.find(f => f.slug === slug);
export const getApplication = (slug: string) => applications.find(a => a.slug === slug);
export const catalogNote = 'Product concepts for OEM / ODM discussion. Packaging artwork is illustrative; formula, label claims, specifications and availability are confirmed for each project.';
