'use client';
import { useEffect, useRef, useState } from 'react';
import { Check, ChevronDown } from 'lucide-react';
type Option={value:string;label:string;count?:number};
export default function BrandSelect({id,label,value,options,onChange,name}:{id:string;label:string;value:string;options:Option[];onChange:(value:string)=>void;name?:string}){
 const root=useRef<HTMLDivElement>(null);const trigger=useRef<HTMLButtonElement>(null);const [open,setOpen]=useState(false);const [active,setActive]=useState(0);const typeahead=useRef('');const typeaheadTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const index=Math.max(0,options.findIndex(o=>o.value===value));const selected=options[index];
 useEffect(()=>{if(!open)return;const close=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[open]);
 useEffect(()=>()=>clearTimeout(typeaheadTimer.current),[]);
 useEffect(()=>{if(!open)return;const menu=document.getElementById(`${id}-list`);const option=document.getElementById(`${id}-option-${active}`);if(menu&&option){const top=option.offsetTop;const bottom=top+option.offsetHeight;if(top<menu.scrollTop)menu.scrollTop=top;else if(bottom>menu.scrollTop+menu.clientHeight)menu.scrollTop=bottom-menu.clientHeight;}},[active,id,open]);
 function choose(i:number){onChange(options[i].value);setActive(i);setOpen(false);trigger.current?.focus();}
 return <div className={`jt-select${open?' is-open':''}`} ref={root} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false);}}>{name&&<input type="hidden" name={name} value={value}/>}<span className="jt-select-label" id={`${id}-label`}>{label}</span><button ref={trigger} type="button" className="jt-select-trigger" role="combobox" aria-labelledby={`${id}-label ${id}-value`} aria-haspopup="listbox" aria-expanded={open} aria-controls={`${id}-list`} aria-activedescendant={open?`${id}-option-${active}`:undefined} onClick={()=>{setActive(index);setOpen(!open);}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);return;}if(e.key==='Tab'){setOpen(false);return;}if(e.key==='Enter'||e.key===' '){e.preventDefault();if(open)choose(active);else{setActive(index);setOpen(true);}return;}if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();setOpen(true);setActive(e.key==='Home'?0:e.key==='End'?options.length-1:!open?index:(active+(e.key==='ArrowDown'?1:-1)+options.length)%options.length);return;}if(e.key.length===1&&!e.ctrlKey&&!e.metaKey&&!e.altKey){typeahead.current+=e.key.toLowerCase();clearTimeout(typeaheadTimer.current);typeaheadTimer.current=setTimeout(()=>{typeahead.current='';},650);const match=options.findIndex(o=>o.label.toLowerCase().startsWith(typeahead.current));if(match>=0){setActive(match);setOpen(true);}}}}><span id={`${id}-value`}>{selected?.label}</span><ChevronDown size={17}/></button>{open&&<div className="jt-select-menu" id={`${id}-list`} role="listbox" aria-labelledby={`${id}-label`}><div className="jt-select-menu-heading" aria-hidden="true">Select {label.toLowerCase()}</div>{options.map((o,i)=><button id={`${id}-option-${i}`} key={o.value} type="button" role="option" tabIndex={-1} aria-selected={o.value===value} className={`${i===active?'is-active ':''}${o.value===value?'is-selected':''}`} onPointerMove={()=>setActive(i)} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(i)}><span className="jt-select-check">{o.value===value&&<Check size={15}/>}</span><span>{o.label}</span>{o.count!==undefined&&<small>{o.count}</small>}</button>)}</div>}</div>;
}
