'use client';
import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { Play, Pause, Volume2, VolumeX, Maximize, Minimize, RotateCcw } from 'lucide-react';
import styles from './production-film.module.css';
const time=(seconds:number)=>`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
const subscribe=()=>()=>{};
export default function ProductionFilm(){
 const video=useRef<HTMLVideoElement>(null);const frame=useRef<HTMLDivElement>(null);
 const enhanced=useSyncExternalStore(subscribe,()=>true,()=>false);const [started,setStarted]=useState(false);const [playing,setPlaying]=useState(false);const [ended,setEnded]=useState(false);const [muted,setMuted]=useState(false);const [position,setPosition]=useState(0);const [duration,setDuration]=useState(37.9);const [fullscreen,setFullscreen]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{const change=()=>setFullscreen(document.fullscreenElement===frame.current);document.addEventListener('fullscreenchange',change);return()=>document.removeEventListener('fullscreenchange',change);},[]);
 async function toggle(){const el=video.current;if(!el)return;if(!el.paused){el.pause();return;}if(el.ended)el.currentTime=0;setError('');try{await el.play();}catch{setError('Playback could not start. Please try again.');}}
 async function expand(){try{if(document.fullscreenElement){await document.exitFullscreen();}else if(frame.current?.requestFullscreen){await frame.current.requestFullscreen();}else{const el=video.current as HTMLVideoElement&{webkitEnterFullscreen?:()=>void};el?.webkitEnterFullscreen?.();}}catch{setError('Full screen is unavailable on this browser.');}}
 return <div className={styles.film} ref={frame} onKeyDown={e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLButtonElement)return;if(e.key===' '){e.preventDefault();void toggle();}if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();if(video.current)video.current.currentTime=Math.min(duration,Math.max(0,video.current.currentTime+(e.key==='ArrowRight'?5:-5)));}}}>
 <video ref={video} className={styles.video} controls={!enhanced} playsInline preload="none" poster="/media/posters/production-line.webp" aria-label="Jentoor production line film" onPlay={()=>{setStarted(true);setPlaying(true);setEnded(false);}} onPause={()=>setPlaying(false)} onEnded={()=>{setEnded(true);setPlaying(false);}} onTimeUpdate={e=>setPosition(e.currentTarget.currentTime)} onLoadedMetadata={e=>{if(Number.isFinite(e.currentTarget.duration))setDuration(e.currentTarget.duration);}} onVolumeChange={e=>setMuted(e.currentTarget.muted)} onError={()=>setError('The film could not load. Please refresh and try again.')}><source src="/media/production-line.mp4" type="video/mp4"/>Your browser does not support video.</video>
 {enhanced&&<><div className={`${styles.cover} ${started&&!ended?styles.coverHidden:''}`}><div className={styles.filmLabel}><span className={styles.dot}/> INSIDE THE PRODUCTION LINE <span>FILM 01</span></div><button type="button" className={styles.heroPlay} onClick={()=>void toggle()} aria-label={ended?'Replay production film':'Play production film'}>{ended?<RotateCcw/>:<Play fill="currentColor"/>}<span>{ended?'PLAY AGAIN':'WATCH THE FILM'}</span></button><div className={styles.coverTitle}><span>Precision,</span><em>in motion.</em></div><span className={styles.duration}>00:38 / PRODUCTION FILM</span></div>
 {started&&!ended&&<div className={styles.controls}><input aria-label="Video progress" className={styles.progress} type="range" min="0" max={duration} step="0.1" value={position} style={{'--progress':`${position/duration*100}%`} as React.CSSProperties} onChange={e=>{if(video.current)video.current.currentTime=Number(e.target.value);setPosition(Number(e.target.value));}}/><div className={styles.controlRow}><button type="button" onClick={()=>void toggle()} aria-label={playing?'Pause film':'Resume film'}>{playing?<Pause size={19}/>:<Play size={19}/>}</button><span className={styles.time}>{time(position)} <span>/ {time(duration)}</span></span><span className={styles.controlTitle}>JENTOOR · INSIDE PRODUCTION</span><button type="button" onClick={()=>{if(video.current)video.current.muted=!video.current.muted;}} aria-label={muted?'Unmute film':'Mute film'}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button><button type="button" onClick={()=>void expand()} aria-label={fullscreen?'Exit full screen':'Full screen'}>{fullscreen?<Minimize size={19}/>:<Maximize size={19}/>}</button></div></div>}
 </>}{error&&<p className={styles.error} role="alert">{error} <a href="/media/production-line.mp4">Open video ↗</a></p>}
 </div>;
}
