/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from 'next';
import { ArrowRight, ArrowUpRight, Boxes, Globe2, PackageCheck, TestTube2 } from 'lucide-react';
import { SiteFooter, SiteHeader } from '../../site-chrome';

export const metadata: Metadata = { title: 'Bterlif Brand Case | Jentoor', description: 'A selected Jentoor brand case connecting supplement product development, manufacturing and ecommerce market readiness.' };

export default function BterlifCasePage() {
  return <main className="inner-page case-page" id="top"><header className="case-hero"><SiteHeader /><div className="shell case-hero-grid"><div><p className="eyebrow"><span /> SELECTED BRAND CASE / BTERLIF</p><h1>From product idea<br />to <em>market presence.</em></h1><p className="inner-lede">A practical brand-building case connecting product direction, scalable manufacturing, packaging execution and ecommerce readiness.</p><div className="case-actions"><a className="primary-button" href="https://bterlif.com/" target="_blank" rel="noreferrer">Visit Bterlif <ArrowUpRight size={17} /></a><a href="/oem-odm">Explore OEM / ODM <ArrowRight size={16} /></a></div></div><div className="case-mark"><span>B</span><b>BTERLIF</b><small>SELECTED BRAND CASE</small></div></div></header>
    <section className="case-overview shell"><div><p className="section-tag">01 / THE BRIEF</p><h2>Build for the product.<br />Plan for the channel.</h2></div><div><p>Bterlif demonstrates how a supplement program can move beyond a generic catalogue decision. Product, packaging, operational readiness and the online customer experience were considered as one connected launch system.</p><p className="case-disclosure">Published as a selected manufacturing case with brand permission. Commercial and confidential project details remain private.</p></div></section>
    <section className="case-chain"><div className="shell"><p className="section-tag light">02 / CONNECTED DELIVERY</p><div className="case-chain-grid">{[[TestTube2,'Product direction','Translate the target customer and product idea into a manufacturable brief.'],[Boxes,'Production system','Align formulation, materials, process controls and repeatable batch execution.'],[PackageCheck,'Pack readiness','Coordinate container, label, coding and shipping resilience for ecommerce.'],[Globe2,'Market route','Prepare a consistent brand presence across direct ecommerce and Amazon.']].map(([Icon,t,c],i) => <article key={String(t)}><Icon /><span>0{i+1}</span><h3>{String(t)}</h3><p>{String(c)}</p></article>)}</div></div></section>
    <section className="testimonial"><div className="shell"><span className="quote-mark">“</span><blockquote>Factory efficiency really stood out throughout the project.</blockquote><p>— ZAC · BRAND LEAD AT BTERLIF</p></div></section>
    <section className="case-outcome shell"><p className="section-tag">03 / THE OUTCOME</p><div><h2>A brand system ready to keep moving.</h2><p>The result is a consumer-facing supplement brand with an independent ecommerce presence and an Amazon sales route, supported by a manufacturing program designed around efficient execution and repeat supply.</p><a href="/insights/how-custom-supplement-formulation-works">Read the formulation guide <ArrowRight size={16} /></a></div></section><SiteFooter /></main>;
}
