import type { Metadata } from 'next';
import { formats, processSteps } from '../_knowledge/content';
import { KnowledgeShell, ProjectCta, SourceLink } from '../_knowledge/chrome';
import s from '../_knowledge/knowledge.module.css';
export const metadata: Metadata = {
  title: 'Custom Supplement Formulation Process | Jentoor',
  description: 'From product brief to delivery: ingredient selection, sample revisions, specification approval, packaging, scale-up and quality release.',
  alternates: { canonical: '/formulation' },
  openGraph: { title: 'Custom Supplement Formulation Process | Jentoor', description: 'A practical guide to inputs, deliverables and approvals at every stage.', url: '/formulation', type: 'website' },
};
export default function FormulationPage() {
  return <KnowledgeShell current="Formulation" title="From first brief" emphasis="to finished batch." intro="A custom formula becomes a reliable product through a series of controlled decisions. Know what to provide, what to expect and what needs approval before moving forward.">
    <section className={`${s.container} ${s.overview}`} aria-labelledby="route-title"><div className={s.overviewHeading}><div><p className={s.kicker}>THE DEVELOPMENT ROUTE</p><h2 id="route-title">One process. Clear checkpoints.</h2></div><p>A planning framework for your project. Packaging exploration can run alongside formulation; final approvals stay linked to controlled versions.</p></div>
      <ol className={s.route}>{processSteps.map((step, i) => <li key={step.id}><a href={`#${step.id}`}><span>{String(i + 1).padStart(2, '0')}</span><strong>{step.short}</strong><span className={s.routeArrow} aria-hidden="true">→</span></a></li>)}</ol>
      <p className={s.loop}><span aria-hidden="true">↶</span> A change to the formula, material, site or package returns to the affected approval stage.</p>
    </section>
    <section className={s.roles} aria-labelledby="roles-title"><div className={s.container}><p className={s.kicker}>AGREE THE OWNERS</p><h2 id="roles-title">Shared work. Defined responsibility.</h2><div className={s.roleGrid}><div><span>01 / BRAND</span><h3>Set direction & approve</h3><p>Own the commercial brief and brand decisions. Arrange qualified market-specific review of formula, label and claims; approve samples, artwork and agreed changes.</p></div><div><span>02 / JENTOOR</span><h3>Coordinate the project</h3><p>Connect development, quotation, production-route review and delivery planning. Confirm the scope, proposed facility and decision owners for the SKU.</p></div><div><span>03 / FACTORY & QUALITY</span><h3>Manufacture & release</h3><p>Control materials, production, records and testing. Factory quality personnel make the batch-disposition decision under the applicable quality system.</p></div></div><p className={s.roleFoot}>Record responsibilities in the project and quality agreements. Brand commercial acceptance does not replace factory quality release.</p></div></section>
    <section className={`${s.container} ${s.stepsSection}`} aria-labelledby="steps-title"><div className={s.sectionHeading}><p className={s.kicker}>INPUT → WORK → OUTPUT → APPROVAL</p><h2 id="steps-title">The decisions behind the product.</h2></div><ol className={s.steps}>{processSteps.map((step, i) => <li className={s.step} id={step.id} key={step.id}><div className={s.stepTitle}><span className={s.number}>{String(i + 1).padStart(2, '0')}</span><h3>{step.title}</h3></div><div className={s.stepContent}><dl className={s.stepGrid}><div><dt>Brand input</dt><dd>{step.input}</dd></div><div><dt>Development / factory work</dt><dd>{step.work}</dd></div><div className={s.output}><dt>Output</dt><dd>{step.output}</dd></div></dl><div className={s.gate}><span aria-hidden="true">◇</span><p><strong>Approval gate</strong>{step.gate}</p></div>{step.source && <SourceLink source={step.source} />}</div></li>)}</ol></section>
    <section className={s.formats} aria-labelledby="formats-title"><div className={s.container}><div className={s.overviewHeading}><div><p className={s.kicker}>FORMAT CHANGES THE ENGINEERING</p><h2 id="formats-title">Nine formats.<br />Product-specific decisions.</h2></div><p>Start with dose, user experience and stability. Confirm the formula, equipment and packaging fit for the proposed production route.</p></div><ul className={s.formatGrid}>{formats.map((format, i) => <li key={format.name}><span className={s.formatIndex}>{String(i + 1).padStart(2, '0')}</span><h3>{format.name}</h3><p>{format.focus}</p></li>)}</ul></div></section>
    <section className={`${s.container} ${s.handover}`} aria-labelledby="handover-title"><div><p className={s.kicker}>BEFORE THE NEXT ORDER</p><h2 id="handover-title">Keep the evidence connected.</h2><p>Review first-batch findings, stability follow-up, complaints and material changes. A reorder should point to the approved formula, specification and artwork versions.</p><a className={s.inlineLink} href="/faq#quality">Read the quality FAQ <span aria-hidden="true">→</span></a></div><div className={s.fileStack}><p>THE CONTROLLED PRODUCT FILE</p><ul><li>Approved brief & quantitative formula</li><li>Sample reference & product specification</li><li>Artwork, package & testing requirements</li><li>Batch records, COA & release status</li><li>Shipment lots & change history</li></ul></div></section><ProjectCta />
  </KnowledgeShell>;
}
