/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages */
import { ArrowUpRight, ArrowRight, FlaskConical, PackageCheck, ShieldCheck, Layers3 } from 'lucide-react';
import { PageShell, ProductCard, SectionHeading, InquiryCta, pageMetadata } from './_catalog/shared';
import { formats, applications, featuredSlugs, getProduct, catalogNote } from './_catalog/data';
import FormulaLab from './components/process-scenes/formula-lab';
import ManufacturingExperience from './components/process-scenes/manufacturing-experience';
import { articles } from './insights/article-data';
export const metadata=pageMetadata('Supplement Manufacturing & Product Catalog','Explore supplement product concepts across seven dosage formats. Connect formulation, packaging and manufacturing for your next OEM or ODM project.','/','/brand/campaigns/nutrition-sculpture.webp');
export default function Home(){return <PageShell>
<section className="jt-home-hero shell"><div className="jt-hero-copy"><p className="jt-kicker"><span className="jt-status-dot"/> FROM CONCEPT TO MANUFACTURING</p><h1>Good ideas.<br/>Thoughtful nutrition.<br/><em>Your next product.</em></h1><p>Explore a world of supplement possibilities. We connect product development, formulation and manufacturing around your next OEM or ODM project.</p><div className="jt-actions"><a className="jt-button" href="/catalog">Explore the catalog <ArrowUpRight size={19}/></a><a className="jt-link" href="/contact">Let’s talk about your idea <ArrowRight size={18}/></a></div><div className="jt-hero-footnote"><span>07 <small>PRODUCT FORMATS</small></span><span>01 <small>CONNECTED APPROACH</small></span></div></div><div className="jt-hero-art"><picture><source media="(max-width: 520px)" srcSet="/brand/campaigns/nutrition-sculpture-mobile.webp"/><img src="/brand/campaigns/nutrition-sculpture.webp" width="1536" height="1024" fetchPriority="high" alt="Conceptual nutrition sculpture: an amber softgel, forest-green capsule and delicate oral film in a sunlit architectural setting"/></picture><div className="jt-art-top"><span>JENTOOR / THE ART OF NUTRITION</span><span>VOL. 01</span></div><div className="jt-art-bottom"><span>Form follows<br/><em>possibility.</em></span><a href="/catalog" aria-label="Explore the product catalog"><ArrowUpRight size={24}/></a></div><span className="jt-art-note">CONCEPTUAL BRAND ARTWORK</span></div></section>
<div className="jt-proof-strip"><div className="shell"><span><FlaskConical size={19}/> Formulation to production</span><span><Layers3 size={19}/> Seven formats to explore</span><span><PackageCheck size={19}/> Packaging considered together</span><a href="/quality"><ShieldCheck size={19}/> Review our quality approach <ArrowUpRight size={16}/></a></div></div>
<section className="jt-section shell" id="catalog"><SectionHeading kicker="01 / THE CATALOG" title="A starting point for something yours." copy="Browse product concepts. Find a direction. Make the details your own." href="/catalog" label="View all 24 concepts"/><div className="jt-product-grid">{featuredSlugs.map(slug=><ProductCard key={slug} product={getProduct(slug)!}/>)}</div><p className="jt-disclosure">{catalogNote}</p></section>
<section className="jt-format-section" id="capabilities"><div className="shell"><SectionHeading kicker="02 / FIND YOUR FORMAT" title="Different formats. Shared attention to detail." copy="Start with how the product will be used, then connect the ingredients, serving and packaging."/><div className="jt-format-grid">{formats.map((f,i)=><a className="jt-format-tile" href={`/catalog/${f.slug}`} key={f.slug} style={{background:f.color}}><span>0{i+1}<ArrowUpRight size={18}/></span><img src={getProduct(f.image)!.thumbnail} width="420" height="420" loading="lazy" alt={`${f.name} packaging concept`}/><h3>{f.name}</h3></a>)}</div></div></section>
<section className="jt-digital-section" id="digital-lab"><div className="shell"><SectionHeading kicker="INTERACTIVE / THE FORMULA ATELIER" title="Explore the form. Discover the possibilities." copy="Rotate, separate and explore the capsule, tablet, powder, liquid, gummy, chewable, softgel, lozenge and oral film studies. Nine interactive format studies complement the seven product catalog categories."/><FormulaLab/></div></section><section className="jt-section shell"><SectionHeading kicker="03 / HOW WE BUILD" title="Where are you starting?" href="/oem-odm" label="Explore OEM / ODM"/><div className="jt-route-grid">{[['01','A product direction','Start with a catalog concept. Review the formula, presentation and customization scope.','/catalog','Find your starting point'],['02','An original idea','Define your audience, ingredient direction and experience. Develop a focused formulation brief.','/formulation','Explore formulation'],['03','An existing specification','Bring your product requirements. Align the process, quality controls and supply expectations.','/oem-odm','Discuss manufacturing']].map(([n,t,c,h,l])=><article key={n}><span className="jt-large-index">{n}</span><h3>{t}</h3><p>{c}</p><a className="jt-link" href={h}>{l}<ArrowUpRight size={17}/></a></article>)}</div></section>
<section className="jt-application-section"><div className="shell"><SectionHeading kicker="04 / APPLICATION DIRECTIONS" title="Build around a daily need." copy="Explore development directions across the catalog. Final formulas and label claims are reviewed for each project." href="/solutions" label="Explore applications"/><div className="jt-application-grid">{applications.slice(0,4).map(a=><a key={a.slug} href={`/solutions/${a.slug}`}><div><img src={getProduct(a.image)!.thumbnail} width="420" height="420" loading="lazy" alt={`${a.name} product concept`}/></div><h3>{a.name}<ArrowUpRight size={19}/></h3></a>)}</div></div></section>
<section className="jt-section shell jt-factory-split" id="factory"><div className="jt-factory-photo"><img src="/media/production-floor.jpg" width="1200" height="900" loading="lazy" alt="Production staff and equipment on the factory floor"/><span>INSIDE THE PROCESS / GUANGZHOU</span></div><div><p className="jt-kicker">05 / MANUFACTURING, MADE VISIBLE</p><h2>Behind every product,<br/><em>a considered process.</em></h2><p>A product is more than its formula. Follow the connection between material review, production, packaging and quality release.</p><div className="jt-factory-points"><a href="/factory"><b>01</b><span>Explore the production floor</span><ArrowUpRight size={19}/></a><a href="/laboratory"><b>02</b><span>Formulation & laboratory thinking</span><ArrowUpRight size={19}/></a><a href="/quality"><b>03</b><span>Documents you can evaluate</span><ArrowUpRight size={19}/></a></div><a className="jt-button" href="/manufacturing">Meet the manufacturing process <ArrowUpRight size={18}/></a></div></section>
<section className="shell jt-digital-production" id="production-line"><SectionHeading kicker="INTERACTIVE / THE PROCESS ATELIER" title="A closer connection to every step." copy="Explore the production-line simulation. Choose a station, rotate the scene, pause the motion and follow the filling and packaging sequence."/><ManufacturingExperience/></section><section className="jt-packaging-band"><div className="shell"><div><p className="jt-kicker">06 / THE COMPLETE PRESENTATION</p><h2>Good packaging starts<br/>with the product inside.</h2><p>Bottles, pouches, canisters and individual films. Consider the serving experience, protection and label together.</p><a className="jt-button jt-button-light" href="/packaging">Explore packaging <ArrowUpRight size={18}/></a></div><div className="jt-pack-images"><img src="/catalog/beet-root-powder/main.webp" width="840" height="840" loading="lazy" alt="Pouch packaging concept"/><img src="/catalog/pumpkin-seed-oil-softgels/main.webp" width="840" height="840" loading="lazy" alt="Bottle packaging concept"/></div></div></section>
<section className="jt-section shell"><SectionHeading kicker="07 / THE BUYER’S NOTEBOOK" title="Better questions. Clearer decisions." href="/insights" label="All buyer resources"/><div className="jt-guide-grid">{articles.slice(0,3).map((a,i)=><a href={`/insights/${a.slug}`} key={a.slug}><span className="jt-kicker">GUIDE 0{i+1} / {a.category}</span><h3>{a.title}</h3><p>{a.description}</p><span className="jt-link">Read the guide <ArrowUpRight size={17}/></span></a>)}</div></section>
<section className="jt-section shell jt-faq-split"><div><p className="jt-kicker">BEFORE WE BEGIN</p><h2>A few useful<br/>first answers.</h2><a className="jt-link" href="/faq">Explore all questions <ArrowUpRight size={18}/></a></div><div className="jt-faq">{[['Are these products ready to order?','The catalog presents product concepts for a manufacturing discussion. Formula, final specifications, packaging, minimum order and availability are confirmed for each project.'],['Can I customize a catalog concept?','Start by describing what should change: ingredients, serving, taste or packaging. Feasibility and development scope are reviewed before a sample or production specification is agreed.'],['What determines minimum order and lead time?','Ingredients, production format, packaging, material availability and development work all influence the quotation. Share your target quantity and market so these conditions can be reviewed together.'],['How do I start a project?','Select one or more concepts, add them to your inquiry and describe your target market, quantity and timeline. You can also start with a custom formula brief.']].map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section><InquiryCta/>
</PageShell>;}
