export type Article = { slug: string; number: string; title: string; description: string; read: string; category: string; intro: string; sections: Array<{ heading: string; paragraphs: string[]; bullets?: string[] }>; };

export const articles: Article[] = [
  { slug:'oem-vs-odm-private-label', number:'01', title:'OEM vs. ODM vs. Private Label Supplements: What Is the Difference?', description:'A practical framework for choosing the right supplement manufacturing model.', read:'8 MIN READ', category:'OEM / ODM', intro:'The labels are useful, but the contract controls the project. Buyers should use OEM, ODM and private label to begin a conversation, then define the actual responsibilities, deliverables, ownership and approval rights.', sections:[
    { heading:'Start with who designs the product', paragraphs:['In a classic OEM project, the buyer brings the formula or detailed specification and asks a manufacturer to reproduce it. ODM adds development work: the partner helps design the formula, delivery system, flavor and manufacturability. Private label usually begins with an established base formula that receives the buyer’s branding and packaging.','Real projects often combine these models. A proven formulation platform may be customized in the places that matter most to the consumer while retaining a lower-risk manufacturing base.'] },
    { heading:'Compare speed, differentiation and control', paragraphs:['Private label can reduce early development work and accelerate sampling. ODM creates more room for product distinction but requires more decisions and validation. OEM gives the buyer strong specification control, provided the formula is complete and technically workable in the selected facility.'], bullets:['Private label: prioritize launch speed and a proven base.','ODM: co-develop around a consumer outcome and commercial target.','OEM: manufacture to a buyer-owned or buyer-approved specification.'] },
    { heading:'Put ownership and change control in writing', paragraphs:['Confirm who owns the finished formula, whether it can be supplied to other buyers and how substitutions are approved. Define what happens when a raw material changes, a branded ingredient becomes unavailable or a packaging component reaches end of life.','The quotation should also state the exact producing facility, testing plan, packaging scope, lead-time assumptions and release documents.'] },
    { heading:'Choose the model from the market backward', paragraphs:['An Amazon launch may emphasize durable packaging, readable product images, barcode placement, replenishment and marketplace documentation. A practitioner brand may prioritize differentiated ingredients and deeper technical substantiation. The channel should shape the product brief before formulation begins.'] }
  ]},
  { slug:'questions-to-ask-supplement-manufacturer', number:'02', title:'12 Questions to Ask Before Choosing a Supplement Manufacturer', description:'A buyer-focused due-diligence checklist for facility, formula, quality and delivery.', read:'9 MIN READ', category:'QUALITY', intro:'A polished quotation is not a qualification file. The right questions reveal whether a partner can connect the producing facility, product specification, quality controls and delivery plan.', sections:[
    { heading:'Confirm the company, site and scope', paragraphs:['Ask which legal entity will contract with you and which physical facility will manufacture the SKU. Request current certificates for that exact site and verify the activities and product formats included in scope. Facility registration is not product approval or endorsement.'], bullets:['Which facility will produce this exact SKU?','Which current certificates apply to that site and format?','Will any production or testing be subcontracted?'] },
    { heading:'Understand the formula and sample process', paragraphs:['Ask how feasibility is reviewed, who approves substitutions and how sample versions are controlled. A final sample should connect to an approved specification and purchase order rather than remain an informal reference.'], bullets:['Who owns the finished formula?','How are dose, excipient and material changes approved?','What marks the sample as final and production-ready?'] },
    { heading:'Define testing and release before production', paragraphs:['The finished-product specification should name relevant limits, methods and acceptance criteria. Confirm which tests are in-house, which are external and whether shipment waits for the agreed release package.'], bullets:['What does the batch-specific COA contain?','How are deviations and out-of-specification results handled?','Can the buyer review documents before shipment?'] },
    { heading:'Make delivery responsibilities visible', paragraphs:['Lead time only becomes meaningful when its start point and dependencies are defined. Confirm printed packaging, materials, laboratory work, Incoterms, importer responsibilities and destination preparation.'], bullets:['What is included in the quotation?','When does the production clock start?','Which party owns customs, import and marketplace preparation?'] }
  ]},
  { slug:'how-custom-supplement-formulation-works', number:'03', title:'How Custom Supplement Formulation Works: From Brief to Scalable Formula', description:'How a commercial idea becomes a manufacturable, testable supplement formula.', read:'10 MIN READ', category:'FORMULATION', intro:'A formula must do more than look compelling on a spreadsheet. It has to fit the dosage form, remain stable, support defensible claims and move consistently through commercial equipment.', sections:[
    { heading:'Begin with the commercial brief', paragraphs:['Define the target consumer, intended benefit territory, sales channel, serving experience, price position, dietary requirements, pack count, launch date and target landed cost. Separate mandatory requirements from preferences so technical teams can solve tradeoffs without changing the product’s core promise.'] },
    { heading:'Translate intent into technical constraints', paragraphs:['Capsule volume, tablet compression, powder flow, liquid solubility, ingredient interaction, flavor and shelf stability shape what is possible. The feasibility review identifies dose limits, excipients, allergens, origins, material lead times and sensory risks.'] },
    { heading:'Prototype with clear approval gates', paragraphs:['Samples should be versioned and evaluated against appearance, taste, mouthfeel, size, serving experience and packaging fit. The approved sample, quantitative formula and specification should point to the same version before scale-up begins.'], bullets:['Feasibility review','Bench prototype','Buyer evaluation','Revision and approval','Pilot or scale-up confirmation'] },
    { heading:'Validate the production system', paragraphs:['Commercial readiness joins formula approval with raw-material specifications, process controls, testing, packaging, artwork and release criteria. A successful formula is not only differentiated; it is repeatable from lot to lot.'] }
  ]},
  { slug:'us-supplement-label-requirements', number:'04', title:'US Dietary Supplement Label Requirements for Private Label Brands', description:'A planning guide for supplement labels, ecommerce content and artwork control.', read:'11 MIN READ', category:'US MARKET', intro:'Label review belongs before printing. A design can look complete while containing the wrong serving, ingredient form, net quantity, business details or claim.', sections:[
    { heading:'Build from the approved formula', paragraphs:['The Supplement Facts panel, ingredient list, serving size and directions must correspond to the approved formula and actual components. Do not copy a competitor panel. Ingredient forms, amounts, units, Daily Values and other ingredients need product-specific review.'] },
    { heading:'Control the five core label elements', paragraphs:['US dietary supplement labels generally include a statement of identity, net quantity of contents, nutrition labeling, ingredient information and the name and place of business of the manufacturer, packer or distributor. Placement, prominence and formatting requirements also matter.'] },
    { heading:'Review claims across every channel', paragraphs:['A physical label, Amazon listing, website, ad, testimonial and influencer script can create one overall marketing message. Structure/function claims require substantiation and must not become disease-treatment promises. FDA does not approve dietary supplements before marketing.'] },
    { heading:'Use a controlled artwork process', paragraphs:['Create one approved copy deck, assign version numbers and separate regulatory, design, barcode and print-proof review. Formula or component changes should trigger a label-impact assessment.'], bullets:['Confirm mandatory statements and responsible-company details.','Match listing images and text to the physical package.','Check barcode, seam, coding, tamper evidence and parcel durability.','Obtain qualified US regulatory review before printing.'] }
  ]}
];
