export type GuideSection = { id: string; heading: string; paragraphs: string[]; bullets?: string[]; sourceIds?: string[] };
export type Article = { slug: string; number: string; title: string; shortTitle: string; description: string; category: string; intro: string; takeaway: string; image: 'production-floor' | 'equipment'; imageCaption: string; steps: string[]; sections: GuideSection[]; checklist: string[]; sourceIds: string[] };

export const sources: Record<string, { title: string; url: string }> = {
  labeling: { title: 'FDA · General dietary supplement labeling', url: 'https://www.fda.gov/food/dietary-supplements-guidance-documents-regulatory-information/dietary-supplement-labeling-guide-chapter-i-general-dietary-supplement-labeling' },
  facts: { title: 'FDA · Supplement Facts panel', url: 'https://www.fda.gov/food/dietary-supplements-guidance-documents-regulatory-information/dietary-supplement-labeling-guide-chapter-iv-nutrition-labeling' },
  claims: { title: 'FDA · Dietary supplement label claims', url: 'https://www.fda.gov/food/dietary-supplements-guidance-documents-regulatory-information/dietary-supplement-labeling-guide-chapter-vi-claims' },
  approval: { title: 'FDA · What FDA approval does and does not mean', url: 'https://www.fda.gov/consumers/consumer-updates/it-really-fda-approved' },
  cgmp: { title: 'FDA · Dietary supplement CGMP guidance', url: 'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/small-entity-compliance-guide-current-good-manufacturing-practice-manufacturing-packaging-labeling' },
  advertising: { title: 'FTC · Health Products Compliance Guidance', url: 'https://www.ftc.gov/business-guidance/resources/health-products-compliance-guidance' },
};
export const mediaUrl = (name: 'production-floor' | 'equipment') => `https://media.jentoor.com/media/${name}.jpg`;
export const imageAlt = (name: 'production-floor' | 'equipment') => name === 'equipment' ? 'Enclosed stainless steel equipment beside a conveyor in a production room' : 'Production team working beside a conveyor and trays on the factory floor';

export const formats = [
  { name: 'Capsules', note: 'Define fill volume, shell choice and units per serving.' },
  { name: 'Tablets', note: 'Review compression, dimensions and coating needs.' },
  { name: 'Powders', note: 'Agree on mixing, flavor and moisture protection.' },
  { name: 'Liquids', note: 'Review solubility, dosing and container compatibility.' },
  { name: 'Gummies', note: 'Evaluate piece size, texture and process exposure.' },
  { name: 'Chewable Tablets', note: 'Balance dose with taste, texture and chewability.' },
  { name: 'Softgels', note: 'Assess fill and shell compatibility together.' },
  { name: 'Lozenges', note: 'Define size, taste and the intended use experience.' },
  { name: 'Oral Dissolving Films', note: 'Review film dimensions, dose capacity and protection.' },
];

export const articles: Article[] = [
  {
    slug: 'oem-vs-odm-private-label', number: '01', category: 'Development & sourcing', shortTitle: 'Choose a manufacturing model',
    title: 'OEM, ODM & private label: choosing your manufacturing route',
    description: 'Compare development scope, formula control and the decisions behind a useful quotation.',
    intro: 'An ingredient list, a product idea and an established formula are three different starting points. Choosing a manufacturing route begins with what your team already knows—and what still needs to be developed.',
    takeaway: 'Use the model to frame the conversation. Use the specification and agreement to define the product.',
    image: 'production-floor', imageCaption: 'Jentoor production-floor photography. The producing site and project scope should be confirmed for each SKU.',
    steps: ['Define the brief', 'Choose development scope', 'Agree ownership', 'Approve specifications'],
    sections: [
      { id: 'starting-point', heading: 'Start with the work, not the acronym', paragraphs: [
        'Suppliers use OEM, ODM and private label differently. A lightly modified base formula may be called ODM by one supplier and private label by another. Ask what will actually be designed, supplied, tested and approved. That answer gives you a more useful comparison than the model name alone.',
        'Write a short brief covering the intended consumer, sales channel, destination, format, serving, pack count, target cost and order quantity. Separate fixed requirements from preferences. A dietary restriction may be fixed; a bottle color may be flexible. This helps the development team solve a tradeoff without quietly changing the core product.'
      ] },
      { id: 'oem', heading: 'OEM: bring a specification that can be reproduced', paragraphs: [
        'OEM usually starts with a buyer-supplied or buyer-controlled formula. It is useful when the brand has technical resources and wants close control over ingredient forms, quantities and acceptance criteria. The manufacturer still needs to review whether those requirements work on the proposed line.',
        'Ingredient names alone are not a complete manufacturing specification. Define the amount per unit and per serving, ingredient forms, assay basis, excipients, shell or coating, packaging and agreed tests. If several of these remain open, include development work in the scope rather than expecting a production quotation to resolve them for free.'
      ] },
      { id: 'odm', heading: 'ODM: develop the product around the brief', paragraphs: [
        'ODM adds development support. The starting point may be a use occasion, a preferred format or a cost target rather than a finished formula. The work can include ingredient selection, sensory development, packaging compatibility and sample revisions. Ask which deliverables are included and which need separate approval or fees.',
        'For example, a powder brief might prioritize a small serving and a mild flavor. Those preferences can conflict with the proposed ingredients. Agree which requirement takes priority, evaluate options and record the decision. A useful development process makes these tradeoffs visible before the commercial formula is locked.'
      ] },
      { id: 'private-label', heading: 'Private label: evaluate the established base', paragraphs: [
        'Private label commonly begins with an established formula and process. It can reduce early development decisions, but material availability, packaging and market review still affect the schedule. Ask what is standard and what can change: shell, flavor, pack size or artwork are separate decisions.',
        'An available formula is not automatically right for your audience or destination. Request the specification, relevant evidence and a sample. A base that fits the product brief may be a sensible starting point; a base that needs major changes should be treated as a development project. FDA does not approve dietary supplements before marketing, so a stock formula should never be presented as FDA approved.'
      ], sourceIds: ['approval'] },
      { id: 'ownership', heading: 'Make “custom” mean something in writing', paragraphs: [
        'Confirm whether the final formula is buyer-owned, licensed or shared, and whether exclusivity has limits by territory, channel or volume. Ask separately about flavor systems, tooling, artwork and test data. Access to a finished product is not the same as access to the information needed to transfer its production.',
        'A hybrid route can be practical: an established base with agreed changes to selected ingredients or packaging. List the unchanged elements and the development elements. Define how substitutions are requested, who evaluates their impact and who approves them before use. Keep the sample, specification and purchase order aligned to one version.'
      ] },
      { id: 'quotation', heading: 'Compare the whole launch, not one bottle price', paragraphs: [
        'Ask each candidate to quote the same formula, packaging, tests and delivery scope. Identify product and component minimums separately, including any surplus printed packaging. Sampling charges, external laboratory work and freight assumptions can change the comparison even when unit prices look similar.',
        'Request milestones tied to dependencies: material readiness, sample approval, artwork approval, production, testing and release. A model name cannot promise a delivery date. End the discussion with a written responsibility list showing what the buyer supplies, what the partner supplies and what still needs a decision.'
      ] },
    ],
    checklist: ['A complete product brief and destination', 'Development deliverables and sample revisions', 'Formula, artwork and data ownership', 'SKU-specific costs, minimums and schedule triggers', 'Written approval and substitution responsibilities'], sourceIds: ['approval'],
  },
  {
    slug: 'questions-to-ask-supplement-manufacturer', number: '02', category: 'Quality & procurement', shortTitle: 'Qualify a manufacturing partner',
    title: '12 questions to ask a supplement manufacturer',
    description: 'Connect the quotation to the producing site, material controls, batch records and release plan.',
    intro: 'A certificate gallery and a competitive quotation are starting points. Qualification means following the evidence all the way from the contracting company to the product you intend to order.',
    takeaway: 'Send the same questions to every candidate. Record which entity, site and product each answer covers.',
    image: 'equipment', imageCaption: 'Jentoor equipment photography. An equipment image does not establish certification or suitability for a particular formula.',
    steps: ['Identify the site', 'Review specifications', 'Agree release evidence', 'Confirm responsibilities'],
    sections: [
      { id: 'site', heading: '01 / Who contracts with us, and who makes the SKU?', paragraphs: ['Ask for the legal entity and the physical producing site. If a partner coordinates several facilities, identify the one proposed for this format. Request a responsibility map covering production, testing, packaging and logistics. Agree how any site change will be reviewed before the order moves.'] },
      { id: 'scope', heading: '02 / What do the qualification documents cover?', paragraphs: ['Request complete, current documents and check the site address, issuing body, scope and validity. A logo on a website is not enough to establish coverage. FDA registration does not mean FDA approval. Confirm any permission needed before using a third-party certification mark on your own packaging.'], sourceIds: ['approval'] },
      { id: 'capability', heading: '03 / What are the format and equipment limits?', paragraphs: ['Connect the broad capability list to your actual product. Ask about the line, batch range, serving capacity and packaging fit. A capsule specification cannot simply be moved to a gummy or oral film. Ask which feasibility questions remain open and what sample or trial will resolve them.'] },
      { id: 'materials', heading: '04 / How are incoming materials controlled?', paragraphs: ['Ask how suppliers are evaluated and how incoming lots are identified, held and released. Specify the ingredient form, source and relevant quality attributes rather than relying on a general ingredient name. For a botanical, request the species and plant part; for a premix, understand the carriers and component information.'] },
      { id: 'formula', heading: '05 / Who develops and controls the formula?', paragraphs: ['Clarify whether the project uses an existing formula, a modified base or original development. Define access to quantitative specifications, confidentiality, ownership and transition rights. Ask how sample versions are linked to the final approved formula so that production cannot follow an earlier revision.'] },
      { id: 'testing', heading: '06 / Which tests determine acceptance?', paragraphs: ['Request a written testing plan linked to the finished-product specification. Ask for methods, limits, sample plans, laboratories and turnaround times. The panel should reflect the formula and format; a generic list of every possible test is not a substitute. Review a representative, redacted COA and agree what the actual batch COA must report.'], sourceIds: ['cgmp'] },
      { id: 'records', heading: '07 / How does the specification become a batch record?', paragraphs: ['Ask how the master manufacturing record is approved and revised, and how each batch records materials, quantities, process steps, checks and packaging. FDA’s dietary supplement CGMP guidance describes master and batch production records and quality-control responsibilities. Use those requirements to guide the discussion, not a claim that any particular site has already met them.'], sourceIds: ['cgmp'] },
      { id: 'minimums', heading: '08 / What creates the real minimum order?', paragraphs: ['Separate finished-product minimums from ingredient and packaging minimums. A printed pouch or custom component may create a larger commitment than the product itself. Ask who pays for unused components, where they are stored and what happens if the artwork changes before they are consumed.'] },
      { id: 'schedule', heading: '09 / What starts—and can pause—the schedule?', paragraphs: ['Request a milestone plan with dependencies. Formula approval, material arrival, artwork, production availability and laboratory release may sit on different timelines. Confirm whether the quoted duration ends at production completion, release or shipment. Record assumptions before comparing suppliers on speed.'] },
      { id: 'changes', heading: '10 / Who approves substitutions and deviations?', paragraphs: ['Ask how a change in material source, carrier, shell, flavor, package or method is proposed and assessed. Agree which changes require buyer approval before implementation. The review should consider specifications, label text, sensory properties and schedule. Also ask how unexpected production events are investigated and communicated.'] },
      { id: 'handoff', heading: '11 / What is included in the delivery handoff?', paragraphs: ['Define the documents supplied before shipment and the person responsible for reviewing them. Clarify freight scope, destination preparation and any external label or import review. “Support” is too broad for a purchase order: name the deliverable, owner and timing, and obtain market-specific advice where needed.'] },
      { id: 'escalation', heading: '12 / What happens when a batch or shipment has a problem?', paragraphs: ['Ask for the escalation route, investigation process and responsibilities for complaints, retained samples and traceability records. Discuss how release is held when results need investigation. A useful answer explains who takes action and what evidence is retained; it does not promise that problems can never occur.', 'Turn the answers into an open-items log. Record the evidence received, the remaining gap and the person responsible for resolving it. Qualification is complete only when the agreed project requirements are addressed—not when every box contains a sales response.'] },
    ],
    checklist: ['Named contracting entity and producing site', 'Current documents with relevant scope', 'Approved specification and batch testing plan', 'Clear release, change and escalation owners', 'Written commercial and delivery dependencies'], sourceIds: ['cgmp', 'approval'],
  },
  {
    slug: 'how-custom-supplement-formulation-works', number: '03', category: 'Formulation & engineering', shortTitle: 'Take a formula into production',
    title: 'From product brief to a manufacturable formula',
    description: 'Understand how serving size, format, sampling and scale-up shape custom formulation.',
    intro: 'A formula is more than a list of ingredients. It is a set of connected decisions about the serving, process, package and evidence needed to make the same product again.',
    takeaway: 'Approve the formula, sample, specification and package as one system before commercial production.',
    image: 'equipment', imageCaption: 'Jentoor equipment photography. The development sequence below is a planning framework, not a validation record for this equipment.',
    steps: ['Brief & feasibility', 'Sample & revise', 'Specify & package', 'Scale & review'],
    sections: [
      { id: 'brief', heading: 'Give the brief a hierarchy', paragraphs: ['Begin with the customer, use occasion, destination and channel. Add the preferred format, serving, pack count, dietary requirements, quantity and target cost. Then distinguish what cannot change from what can be explored. This makes feedback useful when the first prototype exposes a conflict.', 'Consider a brief that asks for a compact serving, several high-dose ingredients and a particular price. Those requests may not fit together. Decide whether serving size, ingredient selection or cost can move. Write that decision into the brief before asking the technical team for another version.'] },
      { id: 'format', heading: 'Choose the format around the serving', paragraphs: ['Jentoor supports capsules, tablets, powders, liquids, gummies, chewable tablets, softgels, lozenges and oral dissolving films. Each format needs a project-specific review. An ingredient list alone does not determine which route is appropriate.', 'Ask different questions for different formats. Capsules require a practical fill and shell; tablets require a workable compression and size. Powders and liquids bring preparation and sensory decisions. Gummies, chewables and lozenges make taste and texture central. Softgels need compatible fill and shell systems, while films require attention to film dimensions and dose capacity. Avoid treating a change of format as a simple packaging change.'] },
      { id: 'ingredients', heading: 'Make the ingredient specification precise', paragraphs: ['Define forms and amounts per unit and per serving. Ask what the assay basis means and whether carriers, flavors, shell materials or other components affect the finished specification. Botanical names should be supported by the relevant species, plant part and extract details. A common name does not establish that two materials are interchangeable.', 'Record which attributes support the intended product positioning and which are preferences. Claims require a separate review of the evidence and exact wording; a manufacturing partner’s ability to make a formula is not proof of a health benefit. For US advertising, the FTC expects health claims to be truthful, not misleading and supported by appropriate evidence.'], sourceIds: ['advertising'] },
      { id: 'feasibility', heading: 'Let the process challenge the concept', paragraphs: ['Ask the production team to identify the questions that could change the formula: fill volume, flow, compression, mixing, heat exposure, solubility or package fit. The relevant questions depend on the product. A feasibility review should explain the proposed adjustment and its effect on the serving, cost and consumer experience.', 'Excipients have technical roles. If a binder, flow aid, flavor or carrier is proposed, ask why it is needed and how it appears in the specification and label review. Removing a component without understanding its role can create a new development problem. Keep each accepted adjustment in the version history.'] },
      { id: 'samples', heading: 'Use samples to answer defined questions', paragraphs: ['Label each sample with a version and preparation instructions. For powders, agree on liquid volume, temperature and mixing method before comparing flavor. For solid formats, record dimensions, serving count and use experience. Consolidate feedback into one revision request rather than sending contradictory comments through several channels.', 'Keep an approved reference sample and record the attributes that matter. Appearance or taste approval does not establish shelf life or production consistency. Identify what still needs testing, scale-up confirmation or packaging review instead of allowing “sample approved” to imply that every technical question is closed.'] },
      { id: 'scale', heading: 'Connect the sample to the commercial system', paragraphs: ['Before production, align the quantitative formula, finished-product specification, process instructions, packaging and artwork. Agree on test methods, acceptance criteria and release responsibilities. FDA’s dietary supplement CGMP guidance describes specifications, production controls and records; the project needs its own documented requirements within the applicable framework.', 'Ask how the selected package will be represented in stability work and what evidence supports any proposed shelf-life statement. During scale-up, compare agreed physical and sensory attributes with the reference, alongside process and laboratory records. Record deviations and decisions so the next batch begins from a controlled version rather than memory.'], sourceIds: ['cgmp'] },
      { id: 'continuity', heading: 'Keep the formula controlled after launch', paragraphs: ['A replacement flavor, ingredient source or packaging component can affect more than purchasing. Route changes through a review of the specification, consumer experience, label and relevant evidence before use. Keep the current approved version accessible to the people ordering materials and releasing product.', 'For the next order, review unresolved issues and relevant feedback alongside production results. The goal is a repeatable product with an understandable history. Development is easier to manage when every decision has an owner, an agreed outcome and a record of what was approved.'] },
    ],
    checklist: ['A ranked product brief and format feasibility review', 'Precise ingredient and serving specifications', 'Versioned sample feedback and approval', 'Packaging, stability and testing responsibilities', 'Documented scale-up and change decisions'], sourceIds: ['cgmp', 'advertising'],
  },
  {
    slug: 'us-supplement-label-requirements', number: '04', category: 'Labeling & market preparation', shortTitle: 'Prepare the label before printing',
    title: 'US supplement labels: a pre-print planning guide',
    description: 'Connect approved formula data, mandatory statements, claims and artwork review before print.',
    intro: 'A label can look finished while its serving, ingredient information or claims still need work. Begin with the approved product specification and make the copy review part of the production plan.',
    takeaway: 'Lock the product information before locking the artwork. This guide is a planning aid, not product-specific regulatory approval.',
    image: 'production-floor', imageCaption: 'Jentoor production-floor photography. Artwork and product-specific release documents are reviewed separately.',
    steps: ['Approve formula data', 'Review label copy', 'Check physical proof', 'Control print version'],
    sections: [
      { id: 'inputs', heading: 'Gather the inputs before opening the design file', paragraphs: ['Bring together the quantitative formula, ingredient specifications, serving instructions, pack quantity, package dimensions and responsible business details. Add the proposed marketing copy and any supporting evidence. Assign someone to resolve inconsistencies before a designer has to make assumptions.', 'Keep a controlled copy deck separate from the artwork. It should identify the product version it describes and the open questions that need qualified review. This makes it possible to distinguish a design change from a change to product information and to review both deliberately.'] },
      { id: 'core', heading: 'Account for the five core statements', paragraphs: ['FDA’s labeling guide identifies five core statements: product identity, net contents, nutrition labeling, ingredient information, and the name and place of business of the manufacturer, packer or distributor. Identity and net contents belong on the principal display panel. Layout, prominence and applicable exceptions also need review.', 'Have the reviewer work from the actual package dimensions. A complete text file does not prove that the printed label has adequate space or legibility.'], sourceIds: ['labeling'] },
      { id: 'serving', heading: 'Build Supplement Facts from the actual formula', paragraphs: ['The Supplement Facts panel needs product-specific serving and ingredient data. FDA’s nutrition-labeling guidance addresses amounts, units, Daily Values and panel format. Ingredient forms and potency information should be reconciled with the quantitative formula rather than copied from another brand’s panel.', 'Check arithmetic separately from design. As a simple example, 60 capsules at two capsules per serving represents 30 servings. These are three different quantities; product imagery and replenishment copy should not confuse them. This example illustrates the count relationship only, not a recommended serving or a finished label.'], sourceIds: ['facts'] },
      { id: 'components', heading: 'Reconcile the full component list', paragraphs: ['Request information for the actual shell, coating, flavor, sweetener and premix components as applicable. Send it through the ingredient and allergen review alongside the active ingredients. A supplier or component change should trigger an assessment of whether the approved label is still accurate.', 'Keep evidence for any voluntary attribute or certification statement in the same review file. Do not assume a facility document gives permission to put a mark on the finished product. Ask what the statement covers and who has authorized its use.'] },
      { id: 'claims', heading: 'Review what the whole message promises', paragraphs: ['FDA distinguishes different claim categories. Structure/function claims require substantiation, the required disclaimer and notification to FDA no later than 30 days after first marketing. Disease claims can cause a product to be regulated as a drug. A disclaimer does not make an unsupported claim acceptable.', 'Review wording together with names, images and surrounding copy. FTC’s health-products guidance addresses express and implied advertising claims and the evidence needed to support them. Keep the package, website and other sales materials aligned with the reviewed message. FDA does not approve dietary supplements or their individual labels before marketing.'], sourceIds: ['claims', 'advertising', 'approval'] },
      { id: 'proof', heading: 'Review a physical proof, then control the version', paragraphs: ['Once the copy is reviewed, compare the artwork with the copy deck line by line. Check the barcode, seam, code location and readable text on the actual package shape. A screen image can conceal a seam conflict or a wrap that makes information difficult to find.', 'Separate content approval from print approval. Name the final file clearly, record its approval and ensure the printer receives that version. Archive obsolete artwork so it cannot accidentally be reordered. Before packing, agree how label versions are checked against the product being run.'] },
      { id: 'scope', heading: 'Define what still needs specialist review', paragraphs: ['The basic label elements are only part of market preparation. Ask the appropriate reviewers about product-specific warnings, allergens, destination rules and any other requirements relevant to the formula and sales route. Define that scope explicitly rather than treating “label support” as a complete service description.', 'A final handoff should contain the approved formula reference, reviewed copy, final artwork, physical proof and open-item resolution. If the formula, supplier, package or marketing claim changes afterward, assess the impact before printing again. The purpose is to keep the product and its description connected through every revision.'] },
    ],
    checklist: ['Approved formula and serving data reconciled', 'Core statements and full component information reviewed', 'Claims and supporting evidence assessed', 'Actual-size proof, seam and code positions checked', 'Final version and change-control owner recorded'], sourceIds: ['labeling', 'facts', 'claims', 'advertising', 'approval'],
  },
];
