/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from 'next';
import { ArrowRight, ArrowUpRight, FileCheck2, FlaskConical, History, ShieldCheck } from 'lucide-react';
import { SiteFooter, SiteHeader } from '../site-chrome';

const assetOrigin = (process.env.NEXT_PUBLIC_ASSET_ORIGIN || '').replace(/\/$/, '');
export const metadata: Metadata = { title: 'Supplement Quality & Compliance | Jentoor', description: 'Qualification, testing, documentation and release systems for supplement manufacturing programs.' };

export default function QualityPage() {
  return <main className="inner-page quality-page" id="top"><header className="inner-hero quality-hero"><SiteHeader /><div className="shell quality-hero-copy"><p className="eyebrow"><span /> QUALITY / COMPLIANCE / EVIDENCE</p><h1>Trust needs<br /><em>a record.</em></h1><p className="inner-lede">We connect facility qualification, product specification, manufacturing controls, testing and release documentation — so buyers can evaluate evidence, not badges.</p></div></header>
    <section className="quality-pillars shell"><p className="section-tag">01 / THE QUALITY CHAIN</p><div className="quality-grid">{[[ShieldCheck,'Qualify','Confirm the exact producing facility, certificate scope and current validity.'],[FlaskConical,'Specify','Define materials, finished-product limits, methods and acceptance criteria.'],[History,'Control','Keep formula, artwork, change, deviation and batch records version-controlled.'],[FileCheck2,'Release','Link representative testing and approved documentation to the finished lot.']].map(([Icon,t,c],i) => <article key={String(t)}><span>0{i+1}</span><Icon /><h2>{String(t)}</h2><p>{String(c)}</p></article>)}</div></section>
    <section className="certificate-band"><div className="shell"><div className="process-heading"><div><p className="section-tag light">02 / VIEW THE EVIDENCE</p><h2>Documents with<br /><em>names, scope and dates.</em></h2></div><p>Certification and registration apply only to the facilities and scopes named in each record. FDA registration does not denote FDA approval.</p></div><div className="document-links"><a href={`${assetOrigin}/certificates/nsf-certificate.pdf`} target="_blank" rel="noreferrer"><span>01</span><b>NSF/ANSI 455-2</b><small>View current record</small><ArrowUpRight /></a><a href={`${assetOrigin}/certificates/factory-qualifications.pdf`} target="_blank" rel="noreferrer"><span>02</span><b>Facility qualification dossier</b><small>ISO, HACCP and registration records</small><ArrowUpRight /></a></div></div></section>
    <section className="split-story shell"><div><p className="section-tag">03 / BUYER DUE DILIGENCE</p><h2>Ask for the records before placing the order.</h2></div><div><p>A responsible qualification review connects the legal entity, site, product format, specification, testing plan and shipment document package.</p><a href="/insights/questions-to-ask-supplement-manufacturer">12 questions to ask a manufacturer <ArrowRight size={16} /></a><a href="/insights">Browse buyer guides <ArrowRight size={16} /></a></div></section><SiteFooter /></main>;
}
