// Evergreen content adapted from the supplied content pack (02, 04, 05, 11, 16, 19, 20).
// Commercial figures and facility credentials require project-specific verification.
export const sources = {
  labeling: { title: 'FDA: Dietary Supplement Labeling Guide', url: 'https://www.fda.gov/food/dietary-supplements-guidance-documents-regulatory-information/dietary-supplement-labeling-guide-chapter-i-general-dietary-supplement-labeling' },
  approval: { title: 'FDA: Is It Really FDA Approved?', url: 'https://www.fda.gov/consumers/consumer-updates/it-really-fda-approved' },
  quality: { title: 'FDA: Dietary Supplement CGMP Guide', url: 'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/small-entity-compliance-guide-current-good-manufacturing-practice-manufacturing-packaging-labeling' },
} as const;
export type SourceKey = keyof typeof sources;
export const formats = [
  { name: 'Capsules', focus: 'Fill volume · powder flow · serving count' },
  { name: 'Tablets', focus: 'Compression · strength · disintegration' },
  { name: 'Powders', focus: 'Mixing · flavor · moisture protection' },
  { name: 'Liquids', focus: 'Solubility · microbial control · closure fit' },
  { name: 'Gummies', focus: 'Heat exposure · chew · active loading' },
  { name: 'Chewable Tablets', focus: 'Taste · texture · compression' },
  { name: 'Softgels', focus: 'Fill compatibility · shell · seal integrity' },
  { name: 'Lozenges', focus: 'Mouthfeel · dissolution · dose uniformity' },
  { name: 'Oral Dissolving Films', focus: 'Film uniformity · loading · moisture barrier' },
];
export type ProcessStep = { id: string; title: string; short: string; input: string; work: string; output: string; gate: string; source?: SourceKey };
export const processSteps: ProcessStep[] = [
  { id:'brief', title:'Define the product brief', short:'Brief', input:'Target consumer, use occasion, intended market and claims, format, serving, pack count, quantity, budget and launch goal. Mark essentials separately from preferences.', work:'Jentoor coordinates the brief review with the development team and identifies missing decisions.', output:'A shared brief with requirements, decision owners and unresolved questions.', gate:'Brand approves the brief and names one person to consolidate decisions.' },
  { id:'feasibility', title:'Test technical feasibility', short:'Feasibility', input:'Benchmark products, dietary exclusions, fixed ingredient requirements and market-review input.', work:'The proposed factory and development team assess dose capacity, ingredient compatibility, processing conditions and equipment fit. Jentoor identifies the proposed production route.', output:'Feasible options, technical tradeoffs, proposed facility and a list of risks to resolve.', gate:'Brand selects a route; technical owners resolve manufacturing blockers and the brand arranges qualified market-specific review.' },
  { id:'formula', title:'Select ingredients and dosage form', short:'Formula', input:'Approved route, ingredient preferences, source restrictions and acceptable serving size.', work:'Development defines exact ingredient forms, amounts per unit and serving, assay basis, carriers, allergens and functional excipients. The factory reviews material and process compatibility.', output:'A versioned quantitative formula and preliminary material specifications.', gate:'Brand approves the formula direction. Formula ownership, confidentiality, exclusivity and substitution rights are agreed in writing.' },
  { id:'commercial', title:'Align scope, cost and schedule', short:'Scope', input:'Order quantity, pack configuration, destination, target cost and required testing or documentation.', work:'Jentoor coordinates a quotation covering ingredients, packaging, testing, development and tooling. Suppliers confirm material minimums and lead-time dependencies.', output:'An itemized scope, quotation assumptions and milestone schedule.', gate:'Both parties agree inclusions, revision allowances, component minimums, payment triggers and the conditions that start or pause the schedule.' },
  { id:'samples', title:'Sample, evaluate and refine', short:'Samples', input:'Consolidated feedback on a named sample version, separating required corrections from preferences.', work:'Development makes prototypes and records revisions. Evaluate size and serving burden, or taste, texture, mixing and aftertaste as appropriate to the format.', output:'A reference sample linked to its formula version, evaluation criteria and revision history.', gate:'Brand signs off the sample against agreed criteria. Unresolved feedback returns to development; sample approval alone does not authorize batch release.' },
  { id:'specification', title:'Approve the specification', short:'Specification', input:'Brand quality requirements, destination requirements, desired shelf life and document expectations.', work:'Factory quality personnel define the product-specific test plan, methods, sampling, limits, laboratory and release authority. Development defines the stability evidence needed for the commercial package.', output:'Controlled product specification, quality agreement, testing plan and stability strategy.', gate:'Technical and quality owners approve the controls; brand accepts the agreed specification and document package before production.' , source:'quality'},
  { id:'packaging', title:'Lock packaging and label artwork', short:'Packaging', input:'Brand files, responsible-business details, approved label copy, barcode requirements and destination receiving rules.', work:'The packaging team evaluates protection from moisture, oxygen, light, leakage and handling. Artwork is checked against the formula, serving, package dimensions and coding plan.', output:'Packaging specification, controlled artwork, printer proof and lot/date-code placement.', gate:'Brand obtains qualified label and claims review and gives written print approval. Factory packaging controls use the approved version.', source:'labeling' },
  { id:'materials', title:'Procure and release materials', short:'Materials', input:'Agreed commercial authorization and approval of any proposed material or packaging changes.', work:'The factory receives and identifies ingredients and packaging, holds them pending required checks, and documents acceptance against specifications.', output:'Released components, traceable material lots and confirmed production readiness.', gate:'Factory quality authorizes material use. Changes affecting formula, label, quality or agreed scope return to the relevant approval gate.' },
  { id:'scale-up', title:'Verify scale-up and manufacture', short:'Scale-up', input:'Approved formula, reference sample and specifications; brand decisions on any scale-up changes.', work:'The factory runs the agreed pilot or scale-up review before routine production. It checks mixing, heating or cooling, filling, yield and packaging as relevant, then records commercial production and in-process checks.', output:'Scale-up findings, controlled manufacturing instructions and completed batch and packaging records.', gate:'Technical and quality owners accept scale-up results. Brand approves changes to agreed product requirements before the commercial route proceeds.' },
  { id:'release', title:'Review results and release the batch', short:'Release', input:'Any agreed brand review of batch documents and shipment acceptance requirements.', work:'Factory quality reviews representative test results, batch records, packaging checks and deviations. Out-of-specification results follow a documented investigation; retesting is not a search for a passing result.', output:'Documented batch disposition, batch-specific COA and agreed release records, with retained samples managed under the quality system.', gate:'Factory quality authorizes release only after applicable requirements are met. Any additional brand document approval is completed before shipment.', source:'quality' },
  { id:'delivery', title:'Deliver and plan replenishment', short:'Delivery', input:'Confirmed destination, receiving contact, shipment instructions and assigned importer, broker and logistics roles.', work:'Jentoor coordinates the agreed shipment documents and handover. The factory links lots to cases; logistics providers follow the agreed shipping and receiving plan.', output:'Reconciled lot list, packing list, invoice, agreed quality documents and delivery records.', gate:'Brand or consignee accepts the delivery and documents. Record discrepancies, complaint contacts and change-control needs before reorder.' },
];
export type FaqItem = { id: string; question: string; answer: string; step?: string; source?: SourceKey };
export const faqCategories: { id: string; title: string; intro: string; items: FaqItem[] }[] = [
  { id:'oem-odm', title:'OEM / ODM & project scope', intro:'Choose a working model and make the responsibilities explicit.', items:[
    { id:'models', question:'What is the difference between OEM, ODM and private label?', answer:'OEM usually starts with a buyer-supplied formula or specification. ODM adds development support to turn a brief into a manufacturable product. Private label usually starts from an established formula. Supplier definitions vary, so the agreement should identify what is existing, modified or newly developed and who approves each deliverable.', step:'brief' },
    { id:'ownership', question:'Who owns a custom formula?', answer:'Ownership depends on the written agreement. Set out rights to the quantitative formula, flavor system, test data, artwork and tooling, including reuse, exclusivity, territory and transfer rights. A custom-development fee does not by itself establish ownership.', step:'formula' },
    { id:'minimums', question:'How are minimum order quantities determined?', answer:'The formula, dosage form, batch size and packaging components can each create a minimum. Request a SKU-specific quote that separates product minimums from printed packaging, specialty ingredients and tooling. Agree how unused components will be stored, charged or disposed of.', step:'commercial' },
    { id:'quote', question:'What should I send for a useful quotation?', answer:'Send the target consumer and market, intended product positioning, format, ingredient requirements, serving and pack count, quantity, packaging preference, target cost and launch goal. Include a formula if you have one, plus required tests and documents. Identify non-negotiable requirements.', step:'brief' },
    { id:'site', question:'How do I confirm the facility for my product?', answer:'Ask for the proposed manufacturing site, its role and the relevant documents for your dosage form. Match the legal name, address, scope and validity of each document to that site. Agree how a site change will be reviewed before production moves.', step:'feasibility' },
  ]},
  { id:'formulation-sampling', title:'Formulation & sampling', intro:'Turn the product idea into a version that can be evaluated and approved.', items:[
    { id:'formats', question:'Which dosage forms can I discuss with Jentoor?', answer:'Capsules, Tablets, Powders, Liquids, Gummies, Chewable Tablets, Softgels, Lozenges and Oral Dissolving Films. The right route depends on dose, ingredient behavior, sensory needs, package protection and the proposed production site. Confirm project-specific feasibility before selecting a format.', step:'feasibility' },
    { id:'convert', question:'Can a capsule formula become a gummy or oral film?', answer:'It needs a new feasibility review. Ingredient loading, taste, heat, moisture and excipient requirements differ. The same ingredient list may require a different serving or formula; samples and specifications must be approved for the new format.', step:'formula' },
    { id:'timing', question:'How long does formulation and sampling take?', answer:'A reliable schedule follows the actual brief, material availability, development complexity and number of revisions. Ask for milestones covering feasibility, materials, sample rounds and approval. Confirm what starts the clock, what feedback is needed and what changes can pause it.', step:'commercial' },
    { id:'feedback', question:'How should I review a sample?', answer:'Use the sample and formula version as the reference. Check the agreed serving, appearance and format-specific attributes such as capsule size, powder mixing, gummy chew or liquid aftertaste. Return one consolidated list of required changes and preferences. Keep the approved reference linked to the final specification.', step:'samples' },
    { id:'sample-production', question:'Does sample approval mean the formula is ready for full production?', answer:'It is one approval gate. The finished specification, testing plan, packaging, artwork and material readiness must also be resolved. Pilot or scale-up review checks whether the formula performs on the selected production equipment.', step:'scale-up' },
  ]},
  { id:'quality', title:'Quality & documentation', intro:'Review the specification, evidence and release decision together.', items:[
    { id:'gmp', question:'Is a GMP certificate enough to qualify a manufacturer?', answer:'A certificate is one piece of evidence. Verify its holder, site, scope, issuer and validity, then review the proposed product controls, representative records, testing and change procedures. Agree the depth of document review and audit needed for the project.', step:'specification' },
    { id:'fda', question:'Are dietary supplements FDA approved?', answer:'FDA does not approve dietary supplements before marketing. Facility registration also does not mean FDA approval. Evaluate the actual manufacturing, quality and market-readiness evidence for the product rather than an approval claim.', source:'approval' },
    { id:'coa', question:'What should I check on a certificate of analysis (COA)?', answer:'Match the product code, lot and specification version to the order. Review test methods, limits, results, units, laboratory and approval status. A raw-material COA does not establish finished-batch quality, and a finished COA summarizes selected results rather than the entire quality file.', step:'release' },
    { id:'tests', question:'Which tests and laboratories should be included?', answer:'Agree a product-specific panel based on ingredients, format, process, destination and quality requirements. Identify methods, limits, sampling, laboratory and which checks are batch-specific. Confirm laboratory competence and method suitability; a generic testing badge does not define the scope.', step:'specification' },
    { id:'failure', question:'What happens if a result is outside specification?', answer:'The batch stays controlled while the factory quality team investigates and documents its disposition. The agreement should define notifications, permitted investigation and retesting, and brand involvement. Shipment follows the approved release requirements, including resolution of relevant deviations.', step:'release', source:'quality' },
    { id:'shelf-life', question:'How is shelf life established?', answer:'Ask what evidence supports the proposed date for the formula in its commercial package and intended storage conditions. Ingredient information alone may not represent the finished product. Agree relevant stability attributes and follow-up work; do not select a date only to meet a sales target.', step:'specification', source:'labeling' },
  ]},
  { id:'packaging-delivery', title:'Packaging & delivery', intro:'Connect the approved product to print, shipment and receiving.', items:[
    { id:'parallel', question:'Can packaging development run alongside formulation?', answer:'Early container and design exploration can run in parallel. Final barrier requirements, serving information and label copy depend on the approved product. Freeze the formula and review the final proof before authorizing print.', step:'packaging' },
    { id:'label', question:'What needs review on a US supplement label?', answer:'FDA identifies five core statements: product identity, net quantity, nutrition labeling, ingredients, and the name and place of business of the manufacturer, packer or distributor. Check the product-specific wording, placement and formatting, plus claims, warnings and other applicable requirements. The brand should arrange qualified final review before printing.', source:'labeling', step:'packaging' },
    { id:'responsibility', question:'Who approves label copy and packaging artwork?', answer:'The brand supplies its business details and marketing copy, arranges market-specific review and gives written print approval. The packaging team checks the physical specification and printer proof. The factory controls the approved artwork version during packaging. Record these responsibilities in the project agreement.', step:'packaging' },
    { id:'production-clock', question:'When does the production lead time start?', answer:'Use the trigger stated in the quotation. Confirm required commercial authorization, formula and sample approval, specifications, artwork, released materials and the production slot. Production, finished testing, release and transit are separate milestones.', step:'materials' },
    { id:'shipment', question:'What is included in the shipment document package?', answer:'Agree it before ordering. It may include a batch-specific COA, specification, lot list, packing list, commercial invoice, transport documents and destination-specific records. Match product names, lots and quantities across files. Assign importer, broker, shipping terms and receiving responsibilities explicitly.', step:'delivery' },
    { id:'changes', question:'Can ingredients or packaging change on a repeat order?', answer:'A supplier, ingredient grade, carrier, flavor, shell, container or artwork change can affect the product. Require an impact review and the relevant approvals before implementation. Confirm the approved formula, specification and artwork versions on every reorder.', step:'materials' },
  ]},
];
